version: '3.8'

services:
  api:
    build: ./api
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes: 
    - ./website:/usr/src/app/
    ports:
    - 5000:5000
  nginx:
    build: ./services/nginx
    environment:
      - VIRTUAL_HOST=your_domain
      - LETSENCRYPT_HOST=your_domain
    ports:
      - 7009:7009
      - 443:443
    depends_on:
      - api
    restart: always