version: '3.8'

services:
  api:
    build: ./api
    command: gunicorn --bind 0.0.0.0:80 app:app
    volumes: 
    - ./api:/usr/src/app/
    
    ports:
    - 5000:5000
  nginx:
    image: nginx:latest
   # environment:
  #    - VIRTUAL_HOST=your_domain
    #  - LETSENCRYPT_HOST=your_domain
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw